### ISSUE TITLE
Server crash when swinging or throwing saber

### ISSUE THREAD

**Issue by C0deMaver1ck** [FiskFille/AdvancedLightsabers#4]
Appears to be caused by 5a22fd9
Attacking or throwing a lightsaber causes this stack trace:

```
java.lang.NoSuchMethodError: net.minecraft.entity.EntityLivingBase.func_70666_h(F)Lnet/minecraft/util/Vec3;
        at fiskfille.lightsabers.common.item.ItemLightsaberBase.getMovingObjectPosition(ItemLightsaberBase.java:119) ~[ItemLightsaberBase.class:?]
        at fiskfille.lightsabers.common.item.ItemLightsaberBase.onEntitySwing(ItemLightsaberBase.java:79) ~[ItemLightsaberBase.class:?]
        at net.minecraft.entity.EntityLivingBase.func_71038_i(EntityLivingBase.java:1184) ~[sv.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147350_a(NetHandlerPlayServer.java:748) ~[nh.class:?]
        at net.minecraft.network.play.client.C0APacketAnimation.func_148833_a(SourceFile:43) ~[ip.class:?]
        at net.minecraft.network.play.client.C0APacketAnimation.func_148833_a(SourceFile:9) ~[ip.class:?]
        at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) ~[ej.class:?]
        at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:165) ~[nc.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:659) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:334) ~[lt.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:547) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```
